### ISSUE TITLE
Reporter fails when running tests with long names

### ISSUE THREAD

**Issue by s-hooshmand** [presidenten/wdio-video-reporter#1]
**Describe the bug**
Operating systems has a limitation on the length of folder/file names. For example Windows poses a maximum of **260** characters. The reporter concatenates, _suite_name+test_name+browser_name+timestamp_ to create a temporary folder for screenshots. This fails the tests if a test has a long name.

**Log**
```
`Using reporter config:[
  [
    null,
    {
      "saveAllVideos": false,
      "videoSlowdownMultiplier": 10,
      "outputDir": "./allure-results/videos",
      "logLevel": "debug"
    }
  ],
  [
    "allure",
    {
      "outputDir": "./allure-results",
      "disableWebdriverStepsReporting": true,
      "disableWebdriverScreenshotsReporting": true
    }
  ],
  "dot",
  "spec",
  "junit"
]

Using config:{
  "debugMode": true,
  "logLevel": "info",
  "videoRenderTimeout": 5,
  "outputDir": "./allure-results/videos",
  "allureOutputDir": "./allure-results",
  "rawPath": "rawSeleniumVideoGrabs",
  "usingAllure": "allure",
  "saveAllVideos": false,
  "videoSlowdownMultiplier": 10,
  "excludedActions": [],
  "jsonWireActions": [
    "url",
    "forward",
    "back",
    "refresh",
    "execute",
    "size",
    "position",
    "maximize",
    "click",
    "submit",
    "value",
    "keys",
    "clear",
    "selected",
    "enabled",
    "displayed",
    "orientation",
    "alert_text",
    "accept_alert",
    "dismiss_alert",
    "moveto",
    "buttondown",
    "buttonup",
    "doubleclick",
    "down",
    "up",
    "move",
    "scroll",
    "doubleclick",
    "longclick",
    "flick",
    "location"
  ]
}





--- New suite: abcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsacaasddsdsdasdasdadaswd ---`
```

**To Reproduce**
Can be produced simply by running the flowing test:
```
import {assert} from "chai";

describe("abcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsacaasddsdsdasdasdadaswd", function(){
     it("abcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcs", function() {
        browser.url("https://webdriver.io");  
        assert.equal(1,2,"error");
    });
});
```

**Expected behavior**
I did a quick check in my forked repository by changing the `generateFilename` inside `helper.js` to just return `browser_name+timestamp` and the problem is resolved.

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 1.2.1
 - **WebdriverIO version:** 5.4.13
 - **Mode:** command line
 - **Node.js version:** 8.11.1
 - **NPM version:** 5.6.0
 - **Browser name and version:** Chrome 68
 - **Platform name and version:** Windows 10

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  73.0.3683.103

**Comment by presidenten** [comment]
Nice find.
In the upcoming v1.2.2 release the filenames will be truncated.
