### ISSUE TITLE
_results_ folder is being generated even outputDir has been defined

### ISSUE THREAD

**Issue by xyngfei** [presidenten/wdio-video-reporter#10]
**Describe the bug**

**To Reproduce**
Just use the wdio-template and define different outputDir.

**Expected behavior**
Default outputDir should be clean up. 

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 1.4.0
 - **WebdriverIO version:** 5.8.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.3.0
 - **NPM version:** 6.7.0

**Comment by presidenten** [comment]
Fixed in version v1.4.1.

Also updated the template project where I noticed I had references to a custom registry, which is now remapped to the official registry so dependency installation with yarn should be possible again.
