### ISSUE TITLE
Using video reporter with chrome headless is blocking popups

### ISSUE THREAD

**Issue by vidya-sundararaman-q2** [presidenten/wdio-video-reporter#31]
**Describe the bug**
When i use the video reporter with chrome headless, browser alert popups are being blocked in the test. 
When i remove video reporter and run the tests in headless mode, the browser popups show up.

**Log**
Please set `wdio.config.logLevel = 'debug'`, then post the whole file called `wdio-0-0-video-reporter.log`.
If it is very large, consider using a gist - http://gist.github.com.

**To Reproduce**
Include code or an example repository that can easily be set up.

A great way to help isolate an issue and thus get a quicker fix, is to fork this repo: https://github.com/presidenten/wdio-template
Check if the issue is existing in the template, otherwise override wdio config with your settings and try to reproduce the test code that causes the issue by using different web controls on Selenium Easy (https://www.seleniumeasy.com/test/) or The Internet (https://the-internet.herokuapp.com/).

**Expected behavior**

**Environment (please complete the following information):**
 - **wdio-video-reporter version: "^2.0.0",
 - **WebdriverIO version:5.18.2
 - **Mode:WDIO Testrunner sync
 
 - **Node.js version:v8.16.0
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:Chrome  79.0.3945.88 
 - **Platform name and version:MacOS
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by presidenten** [comment]
Hi!

The issue template is not there just because it is pretty :-)

Please fill in the blanks properly and make an example by forking https://github.com/presidenten/wdio-template so I have something more substantial to go on.

**Comment by presidenten** [comment]
Closing because of lack of response
