### ISSUE TITLE
logLevel and content files in outputDir

### ISSUE THREAD

**Issue by ff-franciscotavares** [presidenten/wdio-video-reporter#39]
Hi!
According to your documentation, you say: "To see processed messages, set wdio.config.logLevel: 'debug' and check outputDir/wdio-X-Y-Video-reporter.log. This will also leave the screenshots output directory intact for review"

So, I set `logLevel: error` and see these log files and screenshots. 
Actually, do we have any way of just get the videos in outputDir?

**Comment by presidenten** [comment]
Try `logLevel: silent`

**Comment by presidenten** [comment]
@ff-franciscotavares did it work with loglevel silent?
