### ISSUE TITLE
Video which is attaching is not attaching properly and showing the memory in Bytes and it is not playing

### ISSUE THREAD

**Issue by krishnadilips** [presidenten/wdio-video-reporter#41]
**Describe the bug**
Once the execution is completed, video got generated and attaching to the allure report but it the video attached is coming in Bytes and it  is not playable.

**Log**
[wdio-0-0-Video-reporter.log](https://github.com/presidenten/wdio-video-reporter/files/4598380/wdio-0-0-Video-reporter.log)

**To Reproduce**
Run a normal test case with WebdriverIO along with wdio-video-reporter supporting allure reporting and add the code as mentioned in the log file in reporters section in config.js.

**Expected behavior**
Expected to attach the videos properly and they should be played from allure report.

PLEASE BELOW THE SCREENSHOT:

![image](https://user-images.githubusercontent.com/62890222/81396632-64e83f80-9143-11ea-9039-21d87c276599.png)

Also getting below error in console:

ERROR @wdio/local-runner: Failed launching test session: Error: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\Jenkins\workspace\Demo2\recordings\Log-into-account--click-on-Sign-in-Link--CHROME--05-08-2020--13-30-18-432.mp4'
    at Object.statSync (fs.js:932:3)
    at Object.statSync (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\graceful-fs\polyfills.js:308:16)
    at C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:189:70
    at Array.map (<anonymous>)
    at Object.waitForVideosToBeWritten (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:189:33)
    at Video.onExit (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:590:13)
    at process.<anonymous> (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:463:44)
    at process.emit (events.js:323:22)
    at process.EventEmitter.emit (domain.js:482:12)
    at process.exit (internal/process/per_thread.js:165:15)
[0-0] FAILED in chrome - C:\Program Files (x86)\Jenkins\workspace\Demo2\test-suites\demo\EndtoEndTest.js
2020-05-08T08:02:11.577Z INFO @wdio/cli:launcher: Run onComplete hook

**Environment (please complete the following information):**
 - **wdio-video-reporter version:"^2.0.0"
 - **WebdriverIO version:"^6.1.3"
 - **Mode:WDIO Testrunner
 - **Node.js version:v12.16.1
 - **NPM version:6.13.4
 - **Browser name and version:Chrome 81
 - **Platform name and version:Windows 10

**Additional context**
Facing the same issue when we are running from Mac or Windows, it showing the same behaviour.

**Comment by presidenten** [comment]
Linked with issue https://github.com/presidenten/wdio-video-reporter/issues/43

**Comment by presidenten** [comment]
For now, try wdio 5 and node 10. Otherwise we have an eager developer who wants to bump

**Comment by und3fined-v01d** [comment]
@krishnadilips let me know if you need any help with this or if this was resolved?

**Comment by pyxis828** [comment]
I am seeing this happening when I run my tests on Gitlab pipeline.  However, I am getting an error in the beginning of the test run that the video reporter is unsynced. I have tried increasing the timeout, but that hasn't resolved the issue, but I may try increasing it further.  I was previously getting errors about the VideoRender having timeouts as well, but I increased that timeout, and resolved that error.

The error I am seeing: 

`[0-0] 2020-07-06T21:55:45.008Z ERROR @wdio/runner: Error: Some reporters are still unsynced: Video
     at Timeout.setInterval (/builds/qa/ignite-tests/node_modules/@wdio/runner/build/reporter.js:86:25)
     at ontimeout (timers.js:436:11)
     at tryOnTimeout (timers.js:300:5)
     at listOnTimeout (timers.js:263:5)
     at Timer.processTimers (timers.js:223:10)`

config:

```
reporters = ['spec',
    [video, {
        saveAllVideos: false,
        videoSlowdownMultiplier: 50, // Higher to get slower videos, lower for faster videos [value 1-100]
        videoRenderTimeout: 60
    }],
    ['allure', {
    outputDir: './reports/allure-results',
    disableWebdriverStepsReporting: true,
    disableWebdriverScreenshotsReporting: true,
    useCucumberStepReporter: true
    }]
];
    //default 5000
    reporterSyncTimeout: 30000,

```
package.json

```
"dependencies": {
    "@wdio/cli": "^5.18.4",
    "cjson": "^0.5.0",
    "clipboardy": "^2.1.0",
    "moment": "^2.24.0",
    "wdio-video-reporter": "^3.0.0"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^5.16.16",
    "@wdio/appium-service": "^5.18.2",
    "@wdio/cli": "^5.12.5",
    "@wdio/cucumber-framework": "^5.16.15",
    "@wdio/junit-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.18.4",
    "@wdio/mocha-framework": "^5.16.15",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.17.0",
    "appium": "^1.14.0",
    "chromedriver": "^79.0.0",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-image-comparison-service": "^1.8.0"
  }

```

**Comment by jeyaprakash1989** [comment]
I have got same issue with my webdriverio product. Anybody having the solution ?

> **Describe the bug**
> Once the execution is completed, video got generated and attaching to the allure report but it the video attached is coming in Bytes and it is not playable.
> 
> **Log**
> [wdio-0-0-Video-reporter.log](https://github.com/presidenten/wdio-video-reporter/files/4598380/wdio-0-0-Video-reporter.log)
> 
> **To Reproduce**
> Run a normal test case with WebdriverIO along with wdio-video-reporter supporting allure reporting and add the code as mentioned in the log file in reporters section in config.js.
> 
> **Expected behavior**
> Expected to attach the videos properly and they should be played from allure report.
> 
> PLEASE BELOW THE SCREENSHOT:
> 
> ![image](https://user-images.githubusercontent.com/62890222/81396632-64e83f80-9143-11ea-9039-21d87c276599.png)
> 
> Also getting below error in console:
> 
> ERROR @wdio/local-runner: Failed launching test session: Error: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\Jenkins\workspace\Demo2\recordings\Log-into-account--click-on-Sign-in-Link--CHROME--05-08-2020--13-30-18-432.mp4'
> at Object.statSync (fs.js:932:3)
> at Object.statSync (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\graceful-fs\polyfills.js:308:16)
> at C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:189:70
> at Array.map ()
> at Object.waitForVideosToBeWritten (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:189:33)
> at Video.onExit (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:590:13)
> at process. (C:\Program Files (x86)\Jenkins\workspace\Demo2\node_modules\wdio-video-reporter\dist\wdio-video-reporter.js:463:44)
> at process.emit (events.js:323:22)
> at process.EventEmitter.emit (domain.js:482:12)
> at process.exit (internal/process/per_thread.js:165:15)
> [0-0] FAILED in chrome - C:\Program Files (x86)\Jenkins\workspace\Demo2\test-suites\demo\EndtoEndTest.js
> 2020-05-08T08:02:11.577Z INFO @wdio/cli:launcher: Run onComplete hook
> 
> **Environment (please complete the following information):**
> 
>     * **wdio-video-reporter version:"^2.0.0"
> 
>     * **WebdriverIO version:"^6.1.3"
> 
>     * **Mode:WDIO Testrunner
> 
>     * **Node.js version:v12.16.1
> 
>     * **NPM version:6.13.4
> 
>     * **Browser name and version:Chrome 81
> 
>     * **Platform name and version:Windows 10
> 
> 
> **Additional context**
> Facing the same issue when we are running from Mac or Windows, it showing the same behaviour.

**Comment by presidenten** [comment]
@jeyaprakash1989 Would you mind trying with wdio-video-reporter 3.0.0?

**Comment by presidenten** [comment]
@pyxis828 Would you mind forking https://github.com/presidenten/wdio-template and setting up a similar test scenario so I can try to find the error? 
Your slowdown multiplier and timeout seems to be very off. Multiplier 50 would make a huuuuuge file. Try setting it to 2 or 3 instead.

**Comment by presidenten** [comment]
@krishnadilips Have you tried with version 3.0.0 yet?

**Comment by presidenten** [comment]
Just released v3.1.0, that might fix this issue
If anyone of @jeyaprakash1989 @pyxis828 @krishnadilips @und3fined-v01d could verify this, it would be great.

**Comment by und3fined-v01d** [comment]
I'll try to verify this today

**Comment by und3fined-v01d** [comment]
@krishnadilips can you try to provide a minimum steps to reproduce?

**Comment by pyxis828** [comment]
@presidenten for some reason, the email regarding this ended up in my spam folder, ran across it by accident.  So I have actually resolved my issue by reverting to "wdio-video-reporter": "^2.0.0".  Guess I didn't read the docs closely enough at first to see where it was clearly written "For Webdriver IO v5, please use wdio-video-reporter version ^2.0.0." I don't think I'd care to try upgrading again. The config settings I am using for  videoSlowdownMultiplier and  videoRenderTimeout are working fine, although I did need to increase the reporterSyncTimeout to 60000.  My apologies for not updating.

**Comment by und3fined-v01d** [comment]
> @presidenten for some reason, the email regarding this ended up in my spam folder, ran across it by accident. So I have actually resolved my issue by reverting to "wdio-video-reporter": "^2.0.0". Guess I didn't read the docs closely enough at first to see where it was clearly written "For Webdriver IO v5, please use wdio-video-reporter version ^2.0.0." I don't think I'd care to try upgrading again. The config settings I am using for videoSlowdownMultiplier and videoRenderTimeout are working fine, although I did need to increase the reporterSyncTimeout to 60000. My apologies for not updating.

Good to hear that. @presidenten should we mark this as resolved?

**Comment by presidenten** [comment]
Issue seems to be resolved. Thanks for getting back with info @pyxis828
