### ISSUE TITLE
Reporter errors when test name is long (242 char limit)

### ISSUE THREAD

**Issue by trevor-bliss** [presidenten/wdio-video-reporter#48]
**Describe the bug**
CI fails when test name is very long. On the CircleCI docker image I'm running the character limit is 242 characters for the file name. I have confirmed this manually by setting the test name such that the filename produced fails at 243 characters, but passes at 242.

This is very similar to https://github.com/presidenten/wdio-video-reporter/issues/1. Instead of setting the limit to 250, it should be set to 242 *or* be a configurable option.

```
Error: ENAMETOOLONG: name too long, mkdir '/home/circleci/lgc/ui-xxxxxxxxx-components/results/videos/rawSeleniumVideoGrabs/xxx-xxx-xxx--xxxxxxxxx-text-wrapping-and-truncation--in-standard-cells--should-reset-wrap-text-for-cells-of-a-column-and-header-action-changed-to-Clip-Text-when-wrapText-is-changed-to-false-in-columnDefinition--CHROME--07-28-2020--23-50-45-981
```

**To Reproduce**
describe("abcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsacaasddsdsdasdasdadaswd", function(){
     it("abcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcsabcs", function() {
        browser.url("https://webdriver.io");  
        assert.equal(1,2,"error");
    });
});

**Expected behavior**
No errors when a test name is very long.

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 2.0.1
 - **WebdriverIO version:** 6.0.16
 - **Mode:** wdio testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.2
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Linux

**Comment by presidenten** [comment]
Sorry for the long wait! Im finally back after a long vacation and will have a look at this issue. 
Ill make it into an option that defaults to 250chars to be backwards compatible.

I had a few incoming PRs that will be bundled together with the fix. So it will be fixed and released within a week or two.

**Comment by presidenten** [comment]
Fixed in v3.1.0

**Comment by presidenten** [comment]
Check the option `maxTestNameCharacters`

https://github.com/presidenten/wdio-video-reporter#normal-configuration-parameters

**Comment by trevor-bliss** [comment]
Awesome, thank you!
